### ISSUE TITLE
Wrong version range

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/Registrator.jl#103]
Probably related to the fix fo #98, e.g. https://github.com/JuliaRegistries/General/pull/178#discussion_r277581276 from https://github.com/JuliaImages/ImageCore.jl/blob/d7193221cbb4a05009195aea06fb0c94c5b2b28e/Project.toml#L16

**Comment by nkottary** [comment]
So I've deployed this for now https://github.com/JuliaComputing/Registrator.jl/pull/104

This avoids compressing the julia versions.

**Comment by fredrikekre** [comment]
Okay, thanks. But compression is still done for other deps?

**Comment by nkottary** [comment]
Yes.

**Comment by nkottary** [comment]
I think #105 is a better fix. I just learnt that we have a julia directory in the Registry and we can just use that to look up available julia versions.

I've deployed this fix.
