### ISSUE TITLE
Update commit hash when register() is called on a new commit

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaComputing/Registrator.jl#108]
See https://github.com/christopher-dG/tag-bot/issues/3 for tag-bot issue.

Because the commit hash is not updated when register() is called to fix a commit, tag-bot does not tag the correct commit.

**Comment by christopher-dG** [comment]
I believe the fix would be to simply replace the PR body in this branch: https://github.com/JuliaComputing/Registrator.jl/blob/483a76405c722439a7740af45bc53b9bbeecdcd9/src/Server.jl#L744

It's already computed here so it shouldn't be difficult. https://github.com/JuliaComputing/Registrator.jl/blob/483a76405c722439a7740af45bc53b9bbeecdcd9/src/Server.jl#L724-L731

Alternatively we could make sure to only update the commit hash but I'm not sure it makes a difference.
