### ISSUE TITLE
Sorting should be according to "version" and not string.

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/Registrator.jl#11]
See e.g. the sorting in https://github.com/nkottary/General/pull/5/files#diff-c258257db4ab0edbe4ee02a9dc78bb2a.

**Comment by fredrikekre** [comment]
From the same diff, it would also be nice to keep the order in the `Package.toml` file, i.e. `name`, `uuid`, `repo`.

**Comment by StefanKarpinski** [comment]
I actually think the better way to do this is to make natural sort the default sort order for TOML keys and such. The way stuff is currently written is through the Pkg.TOML package so registrator doesn't really have any control over this.

**Comment by KristofferC** [comment]
TOML supports giving a sort `by` argument (which we use in Pkg).

**Comment by StefanKarpinski** [comment]
Sure, but natural sort is the right sort order that TOML should just default to so we might as well do that.

**Comment by nkottary** [comment]
Fixed for versions file: https://github.com/nkottary/General/pull/5/files
