### ISSUE TITLE
run Registator with a newer Julia?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaComputing/Registrator.jl#114]
It seemed safe to just copy the new `compress_versions` into Registrator, but it means that the version compression code is using the old compression so we see things like this:

https://github.com/JuliaRegistries/General/pull/258/files#r278166434

There are a few options:

1. Change Registrator to monkey-patch `Pkg.Types.compress_versions`.
2. Update only Pkg in the Julia that runs Registrator.
3. Update all of the Julia that runs Registrator to a newer version.

Not sure what the best course of action is, but we should do something here.

**Comment by iamed2** [comment]
Option 1 is the nicest for our manual private registration process, followed by Option 3

**Comment by StefanKarpinski** [comment]
Ok, we can go with Option 1 then. It also has the advantage that I'm pretty sure I can deploy that change myself without @nkottary's help 😄

**Comment by nkottary** [comment]
What does monkey patching involve? Just a one liner `import Pkg.Types.compress_versions` ?

**Comment by StefanKarpinski** [comment]
Yeah, that is about it.
