### ISSUE TITLE
Fix issues with getting Registrator commit

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaComputing/Registrator.jl#118]
https://github.com/JuliaComputing/Registrator.jl/commit/171d0722222d9bca6352852c811f8f5074393643#commitcomment-33321721

**Comment by nkottary** [comment]
Is there a way to get this via `Pkg.status`? I tried `Pkg.Display.status(Pkg.Types.Context())`. That gives me the sha's for all the `add`ed packages but does not give the sha for `dev`ed packages.

**Comment by StefanKarpinski** [comment]
I presume you’re asking @iamed2...

**Comment by nkottary** [comment]
I'm generally asking how one can get the sha of an installed package. `Pkg.status` prints it out but doesn't return it as a value

**Comment by nkottary** [comment]
I've review commented on the above PR about the way to get the hash of a package. If there is a better way let me know else we can merge that PR.

**Comment by nkottary** [comment]
Not fixed yet: https://github.com/JuliaComputing/Registrator.jl/pull/121#discussion_r279294393

**Comment by nkottary** [comment]
Tree SHA is good enough to look up the commit of Registrator.
