### ISSUE TITLE
Verification of dependencies

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/Registrator.jl#12]
https://github.com/KristofferC/OhMyREPL.jl/pull/154 adds an (intentionally) faulty dependency that doesn't exist in the registry.

The PR to the registry seems to go through fine though [*edit*: the PR got updated so this link is no longer valid]:  https://github.com/nkottary/General/pull/5/files#diff-74aa886f65423fb0e2de436bd6efc5baR26. This will likely break the package manager.

**Comment by fredrikekre** [comment]
`Crayonsfdfds` could exist in some other registry though? Will it not be possible to depend on packages from other registries?

**Comment by KristofferC** [comment]
At least not in the General registry imho.

**Comment by StefanKarpinski** [comment]
I think that it should be a per-registry policy choice whether each registry is self-contained or not. Agree that General should be self-contained.
