### ISSUE TITLE
Nicer error messages for common errors.

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/Registrator.jl#16]
When we hit an error that is "expected", i.e. is nothing wrong with Registrator itself we should probably try to give a nice error message and not dump an unrelated stacktrace, cf:

https://github.com/JuliaComputing/Registrator.jl/issues/15

**Comment by fredrikekre** [comment]
It would also be nice not to post the issue on this repository when the error is meant for the package maintaner. It would be better to just include the information directly in the comment, e.g. https://github.com/KristofferC/OhMyREPL.jl/pull/157#issuecomment-463635034 in this case.

**Comment by tanmaykm** [comment]
looks like it is now handled everywhere except [here](https://github.com/JuliaComputing/Registrator.jl/blob/3f436ac81b003cfcad8e2c0ae14c03f72bccc892/src/register.jl#L137) which checks if package name has changed
