### ISSUE TITLE
register() seems like it could be accidentally invoked

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/Registrator.jl#17]
A bit of bike shedding but `register()` seems like it can occur in normal code people paste. Perhaps we should have something more name spaced to invoke Registrator?

**Comment by tanmaykm** [comment]
The pattern is now configurable during deployment.

How about a convention like `/register/repo()`.
E.g.: `/register/JuliaRegistries/General()` and `/register/JuliaComputing/JuliaPro()`

**Comment by KristofferC** [comment]
Or you need a `@Registrator` (without the code quote) to invoke the registration bot (similar how you call for @nanosoldier).? This is perhaps orthogonal to choosing a specific register to register to.

**Comment by tanmaykm** [comment]
Will update the pattern to: @JuliaRegistrator `register(...)`
