### ISSUE TITLE
version specifier should be "expanded"

### ISSUE THREAD

**Issue by KristofferC** [JuliaComputing/Registrator.jl#19]
We shouldn't put version specifiers in semver form directly into the registry. Instead they should be expanded like:

```
julia> Pkg.Types.semver_spec("1.0, ^2.0")
VersionSpec("[1.0.0-1, 2.0.0-2]")
```

and that version span should be used.

**Comment by tanmaykm** [comment]
@KristofferC could you elaborate where this should be used?

**Comment by KristofferC** [comment]
The situation is slightly unfortunate. The way version ranges are stored in the registry (for example https://github.com/JuliaRegistries/General/blob/master/N/NearestNeighbors/Compat.toml) are in one form which is read by https://github.com/JuliaLang/Pkg.jl/blob/b807801a7749e42d34e4157d24aa6ecaf50a95bb/src/versions.jl#L189.

In Project files, we give compatibility according to https://julialang.github.io/Pkg.jl/v1/compatibility/#Version-specifier-format-1.

What translates from project file compatibility format to `VersionSpec` format is `Pkg.Types.semver_spec`.

 You can see how it is used for my WIP registrator at https://github.com/JuliaLang/PkgDev.jl/pull/144/files#diff-7948a226cb372a8c3caf7adb013617b1R149.

**Comment by KristofferC** [comment]
Here is an example: https://github.com/KristofferC/OhMyREPL.jl/pull/163#issuecomment-467974732.

This is not an invalid version specifier. it corresponds to

```
julia> Pkg.Types.semver_spec("^0.5")
VersionSpec("0.5.0-0.5")
```

**Comment by tanmaykm** [comment]
Thanks, I see that now. Will send a PR.
