### ISSUE TITLE
Keep key order in Package.toml

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/Registrator.jl#51]
Would be nice to keep the order, `name`, `uuid`, `repo` instead of `name`, `repo`, `uuid`, see e.g. https://github.com/nkottary/General/pull/35/files

**Comment by fredrikekre** [comment]
Also, should `authors` be listed in the registry?

**Comment by StefanKarpinski** [comment]
I think that the TOML files should just be written out in standard alphabetical order, no?

**Comment by fredrikekre** [comment]
I don't know, `Project.toml` files are written in a specific order, maybe match that?

**Comment by StefanKarpinski** [comment]
Sure, that would be fine I guess.
