### ISSUE TITLE
pre-release version is allowed?

### ISSUE THREAD

**Issue by tkf** [JuliaComputing/Registrator.jl#55]
I tried to register `0.2.2-DEV` https://github.com/tkf/Transducers.jl/commit/9d5ff06c5c6089eee1f44b0e4a4bd8919de6d1ec and it actually worked https://github.com/nkottary/General/pull/39

Is it expected?  Can Pkg handle it?

**Comment by fredrikekre** [comment]
No, that should not be allowed IMO.

**Comment by nkottary** [comment]
Fixed now.
