### ISSUE TITLE
Register Registrator?

### ISSUE THREAD

**Issue by iamed2** [JuliaComputing/Registrator.jl#61]
Registrator does not appear to be registered in General, despite having tagged versions.

**Comment by nkottary** [comment]
@StefanKarpinski Can you install Registrator on this repo? https://github.com/apps/juliaregistrar/installations/new

I don't have access to do that.

**Comment by iamed2** [comment]
Done

**Comment by nkottary** [comment]
Thanks.

@JuliaRegistrator register()

**Comment by B4rtDC** [comment]
@JuliaRegistrator register()

**Comment by Mitchell-Mirano** [comment]
Hi, I want to register the main branch of my package, it can be found at https://github.com/Mitchell-Mirano/NumericalMethods.jl, I already installed the Registrator app and created a release.

**Comment by DilumAluthge** [comment]
This repo is for the development of the Registrator.jl package itself.

For instructions on registering your own package, please read the following:

1. https://github.com/JuliaRegistries/Registrator.jl/blob/master/README.md
2. https://github.com/JuliaRegistries/General/blob/master/README.md

If you need more help with registering your package, please ask further questions on Discourse: https://discourse.julialang.org
