### ISSUE TITLE
Dependencies not found?

### ISSUE THREAD

**Issue by caseykneale** [JuliaComputing/Registrator.jl#68]
So I tried to register my package again today, and it seems like the julia registrator can't find the dependancies which I'm um downloading from the registry?

https://github.com/caseykneale/ChemometricsTools.jl/issues/5
Error while trying to register: Error in [deps]: Package 'CSV' with UUID: 336ed68f-0bac-5ca0-87d4-7b16caf5d00b not found in registry or stdlib

Any advice appreciated. I'd love to help here, but I have no idea whats going on.

**Comment by BenJWard** [comment]
It could be that CSV has not been tested and added to the registry yet? So when you try to register ChemometricsTools, it results in a dependency error.

**Comment by BenJWard** [comment]
There is a CSV package, have you checked the UUID, and the version of CSV you're using?

**Comment by caseykneale** [comment]
Hmm I did use Pkg.update before pushing. I'll have to dig through the registry. Is registrator just reading off of General?

**Comment by iamed2** [comment]
That's the correct UUID for CSV: https://github.com/JuliaRegistries/General/blob/master/C/CSV/Package.toml#L2

**Comment by nkottary** [comment]
The app was registering to https://github.com/JuliaRegistries/Test which is mostly an empty registry. I've set the `registry_deps` to General now in the config. So this should no longer be a problem.
