### ISSUE TITLE
Make clear that the tag should be created after PR is merged

### ISSUE THREAD

**Issue by fredrikekre** [JuliaComputing/Registrator.jl#70]
The message here: https://github.com/caseykneale/ChemometricsTools.jl/issues/5#issuecomment-481191532 should IMO be updated to make clear that the tag should not be created until the registry PR is merged.

**Comment by fredrikekre** [comment]
I would also suggest that it is updated to only recommend pushing the newly created tags:
```
git push <tag_name>
```
instead of 
```
git push --tags
```

**Comment by tpoisot** [comment]
Ok _thank you_ for that, I spent about 40 minutes slowly but steadily losing my mind.
