### ISSUE TITLE
Bug in compat test with comma-separated versions

### ISSUE THREAD

**Issue by timholy** [JuliaComputing/Registrator.jl#93]
See https://github.com/JuliaRegistries/General/pull/126

**Comment by fredrikekre** [comment]
Fixed by #90 but unclear why it has not been deployed yet, @nkottary ?

**Comment by nkottary** [comment]
Its deployed now. I apologise for the delay.

**Comment by nkottary** [comment]
A better fix #97 has been deployed now.
