### ISSUE TITLE
julia bounds produce invalid compat entries

### ISSUE THREAD

**Issue by timholy** [JuliaComputing/Registrator.jl#98]
https://github.com/JuliaRegistries/General/pull/178

**Comment by nkottary** [comment]
Fixed this just now. Try calling register() again.

**Comment by fredrikekre** [comment]
Try to retrigger, see https://github.com/JuliaComputing/Registrator.jl/pull/97#issuecomment-485400469

**Comment by timholy** [comment]
Seems fixed, thanks!
